### ISSUE TITLE
[NIRPS] Run LBL on NIRPS-HA

### ISSUE THREAD

**Issue by njcuk9999** [njcuk9999/lbl#26]

**Comment by njcuk9999** [comment]
@CharlesCadieux  could you add the steps here that you currently have to do (I'll copy them into the description)

**Comment by CharlesCadieux** [comment]
We have two screens opened on nirps-client@maestria: lbl_nirps_ha_full and lbl_nirps_ha_friend that compute LBL with the target star as a template or a template 'friend' closest in effective temperature between Proxima, GL514, and HD85512.

To launch LBL on all NIRPS-HA, we open those screens and launch python wrap_full.py or wrap_friend.py.
