### ISSUE TITLE
[LBL] Add HARPS (ESO and ORIG) modes

### ISSUE THREAD

**Issue by njcuk9999** [njcuk9999/lbl#29]
Currently we support the original mode but should also support the ESO mode

- [ ] Find HARPS data reduced with the ESO pipeline
- [ ] Add classes to LBL for both ORIG and ESO
- [ ] Test with `test_data.py`

**Comment by CharlesCadieux** [comment]
Yes, the example data sets `Proxima_HARPS_ESO.tar.xz` and `Proxima_HARPS_ORIG.tar.xz` are now on `/spirou/cook`
