### ISSUE TITLE
LBL drift not computed (v0.7.288)

### ISSUE THREAD

**Issue by clairem789** [njcuk9999/lbl#40]
Hello, I have no clue why the drift file is not compiled from the LBL after a couple of tries. Many (49200) lblrv/FP_FP files have been computed and are present, and my lbl_run.ini file looks like this: 

RUN_LBLREF = False
RUN_LBLMASK_FP = False
RUN_LBLCOMPUTE_FP = False
RUN_LBLCOMPILE_FP = True
RUN_LBLMASK_SCI = False
RUN_LBLCOMPUTE_SCI = False
RUN_LBLCOMPILE_SCI = False

SKIP_LBLREF = True
SKIP_LBLMASK_FP = True
SKIP_LBLCOMPUTE_FP = True
SKIP_LBLCOMPILE_FP = False
SKIP_LBLMASK_SCI = True
SKIP_LBLCOMPUTE_SCI = True
SKIP_LBLCOMPILE_SCI = True

I got this error:
2023-10-30 13:16:58.806|I| Producing LBL RDB 1 table
  0%|                                                                               | 4/49200 [00:02<8:40:39,  1.57it/s]
2023-10-30 13:17:01.347|E| Unexpected lbl_compile.py error: <class 'IndexError'>: boolean index did not match indexed array along dimension 0; dimension is 26423 but corresponding boolean dimension is 25400
12:17:01.364-**|LBLCOMPILE_FP[00000]| QUALITY CONTROL SUCCESSFUL - Well Done -

What can I do?
thanks!

**Comment by CharlesCadieux** [comment]
Hello Claire,

This error suggests that the number of lines is different between FP files. This could mean that some FP files were computed with an older combination of template + mask. Unfortunately, this could require to re-compute all FP files with a single template from which a single mask is produced.

**Comment by clairem789** [comment]
Thanks Charles. I cleaned and restarted the computation of all FPs... answer in a few days
