### ISSUE TITLE
[LBL] Problem with templates at least with HARPS/HARPSN

### ISSUE THREAD

**Issue by njcuk9999** [njcuk9999/lbl#54]
@CharlesCadieux and @eartigau have you looked at any of the hotter star templates coming through LBL recently?

I've have several people with different data sets saying they are seeing weird saw-tooth problems which look like a blaze issue.

So I looked in to the data on `/space/spirou/LBL/HARPS/templates`  (i.e. from August 2023, v0.60.0 from 2023-07) and I can see the problem in targets there:

HD104067  (K2) [from `/space/spirou`] HARPS after LBL telluric correction
![image](https://github.com/user-attachments/assets/565ba8d0-c85c-4a19-b814-30af65bea961)

51 Peg (G2) [from `/space/spirou`] HARPSafter LBL telluric correction
![image](https://github.com/user-attachments/assets/aeed7c5a-6d03-4228-954e-2f4b91fcd625)

I also did two targets locally (the ones that people told me were bad) and get the same problems with the most recent version of LBL

Vega (A0) [done locally] HARPSN no telluric correction done (just the LBL template step)
![image](https://github.com/user-attachments/assets/54820fbd-e807-421f-acc3-82cd8f6f1aa1)

Tau Cet (G8) [done locally] HARPS no telluric correction done (just the LBL template step)
![image](https://github.com/user-attachments/assets/dcc55dda-4dd7-426a-b406-b318efb2e884)

I can't see this in proxima but its a lot harder to see these sort of structures at lower temperature.

So there is really something off with the blaze for the template making.
Note with Vega I check the blaze is from the same night, so its not that the instrument changed also for Tau Cet all the data is from the same year, so again it isn't that the blaze is too far away from the source.

I think we need to fix this ASAP - it seems the LBL RVs are still "good" but that probably just means LBL compile is rejecting all those lines near the edges - which means even in PROXIMA we are probably removing a lot of signal.

**Comment by njcuk9999** [comment]
Just for reference PROXIMA from `/space/spirou`, not obvious that the problem is there but I'm assuming it is given the other stars

![image](https://github.com/user-attachments/assets/b2eb01f3-e1fe-4f98-b2ff-2f366b29634d)

**Comment by CharlesCadieux** [comment]
Hello @njcuk9999 ,

Thanks for looking into this. For HARPS, have you provided any BLAZE_FILE while running LBL_TEMPLATE? I think by default we were always using an old 2014 Blaze file, which was probably good for the Proxima datasets in 2016, but maybe too old now for 2023 data as it looks like the saw-tooth shapes are asymmetric.

**Comment by njcuk9999** [comment]
I've tried forcing one but in my "local attempts" I actually get the correct one from the header (and have it on disk).
I can share the vega and tau ceti data sets if you want to try. 

For vega I have a blaze from 2014 through to 2019, and science data mostly from 2016. Also the blaze file is not forced so its really using the one from the header.

I've tried just opening science spectra and the "correct" blaze file and the blaze files don't seem to match well in all orders - and we use the blaze to construct the weights for the s1d so the problems just get worse.

I'm not sure why we haven't seen this before (but as I say its hard to see anything in Proxima)

**Comment by njcuk9999** [comment]
I've looked through the code and it seems to not be a simple bug (like just applying a blaze twice or not applying it) - I guess we should check hot stars for other instruments as well but yer this problem is not new (at least a year old)

**Comment by njcuk9999** [comment]
From Etienne: 

> There is a mismatch between the blaze and spectrum density definitions. The spectra are expressed as a density in wavelength space rather than pixel space, which implies that one needs to account for the dispersion (multiply by the gradient of wavelength) to convert back to the pixel-space density.


Verified that this is also a problem for ESPRESSO data so that makes three instrument+modes effected:
- [ ] HARPS ORIG
- [ ] HARPS N ORIG
- [ ] ESPRESSO 

For sure the following instruments are not effected:
- [ ] SPIROU (APERO & CADC)
- [ ] NIRPS (APERO & CADC)

Need to check a lbl template for an early star (G or earlier) on the following:
- [ ] NIRPS ESO
- [ ] HARPS ESO
- [ ] HARPS N ESO

Do we need to check any other instruments?
- [ ] CARMENES
- [ ] CORALIE
- [ ] MAROONX [blue/red]
- [ ] SOPHIE


@CharlesCadieux  if you have any templates of early type star for these instrument+modes could you confirm whether we see it or not (or whether we even have data or these instrument+modes) I only have Mdwarfs which its is near impossible to see this effect.

**Comment by njcuk9999** [comment]
Vega spectrum with HARPS N + ORIG (after bug fix):
![image](https://github.com/user-attachments/assets/1d071c06-c563-45ca-9970-9bf87a95e386)

**Comment by njcuk9999** [comment]
I guess if we have no HARPS+ESO NIRPS+ESO data on disk I can get some from DACE.

I think for HARPS+ESO     NIRPS+ESO   we use the blaze corrected files by default but we now have the option to use non-blaze corrected so need to verify these have the same problem too!
