### ISSUE TITLE
Custom magic bins

### ISSUE THREAD

**Issue by astronasko** [njcuk9999/lbl#55]
Hello, is there an quick/elegant way to set custom wavelength boundaries of magic bins? I had a go at overwriting `magic_grid` directly in `Instrument.get_uniform_binned_parameters()`, but I could not get far. Thanks!

**Comment by njcuk9999** [comment]
I'm not sure which magic grid you are talking about, the is one used in getting the "regions" vrad parameters and another used in the telluric cleaning, and another used in the template creation, but the "main lbl" code (compute/compile) deal with the s2d so don't use magic grid.


## For the "regions" vrad

Note that `get_uniform_binned_parameters` only affects the LBL columns with the regions (in wavelength/pixel space) 
i.e. `vrad_XXX-YYY` and `svrad_XXX-YYY`

If this is what you want to change each instrument has a definition of bands in the `get_binned_parameters` function - you could change that for an instrument (I would only do this for new instruments though)
I'm not sure you want to change the default.Instrument.get_uniform_binned_parameters  but if you are adding a new instrument you can override this function in that class (as long as the inputs/outputs are the same this should work.


## For other magic grid (and "regions" not using a wave bin criteria from `get_uniform_binned_parameters`

You can also change the default wave min and max for the regions that don't force wavelength bins you can do this in your wrap file just add:

```
rparams['COMPIL_WAVE_MIN'] = XXX
rparams['COMPIL_WAVE_MAX'] = YYY
rparams['COMPIL_NUM_UNIFORM_WAVEBIN'] = ZZZ
```

XXX and YYY here are in nm and Z is a positive integer.

That will give you the ability to change the start and end and number of bins - if that is enough?

This will change the XXX and YYY throughout LBL which is more generally changing the parameters for the magic grid (for example the one used to generate the template, if the rough ccf, in tellu_clean etc).


In general unless you are adding a new instrument I'd advise against changing the code, and even then I'd keep changes to my new instrument only.

**Comment by astronasko** [comment]
Thank you, this answered my question. I had the "regions" vrad parameters in mind; thank you for maintaining such a nice project.
