### ISSUE TITLE
KeyError when running wrapfile

### ISSUE THREAD

**Issue by doddo15** [njcuk9999/lbl#61]
I'm running lbl for SPIROU_CADC instrument and have created the wrap file, and am able to run it. According to my log, the template and mask tasks complete successfully, and my error is in the lbl_compute phase. I am running with the following wrap parameters: 

> 2024-12-04 10:08:56.704|I| 
2024-12-04 10:08:56.704|I| *******************************************************************************
2024-12-04 10:08:56.704|I|      LBL Compute
2024-12-04 10:08:56.704|I|              VERSION: 0.64.015
2024-12-04 10:08:56.705|I|              INSTRUMENT: SPIROU_CADC
2024-12-04 10:08:56.705|I| *******************************************************************************
2024-12-04 10:08:56.705|I| 
2024-12-04 10:08:56.705|I| User keyword arguments:
2024-12-04 10:08:56.705|I|      INSTRUMENT="SPIROU"
2024-12-04 10:08:56.706|I|      DATA_DIR="/media/dom/big_honkin/files/data/TOI1449_data_tfiles"
2024-12-04 10:08:56.706|I|      DATA_SOURCE="CADC"
2024-12-04 10:08:56.706|I|      DATA_TYPE="SCIENCE"
2024-12-04 10:08:56.706|I|      OBJECT_SCIENCE="TYC_3154-921-1"
2024-12-04 10:08:56.706|I|      OBJECT_TEMPLATE="TYC_3154-921-1"
2024-12-04 10:08:56.707|I|      BLAZE_CORRECTED="False"
2024-12-04 10:08:56.707|I|      SKIP_DONE="True"
2024-12-04 10:08:56.707|I|      PLOT="True"
2024-12-04 10:08:56.707|G| Mask directory exists (Path=/media/dom/big_honkin/files/data/TOI1449_data_tfiles/masks)
2024-12-04 10:08:56.707|G| Templates directory exists (Path=/media/dom/big_honkin/files/data/TOI1449_data_tfiles/templates)
2024-12-04 10:08:56.708|G| Calib directory exists (Path=/media/dom/big_honkin/files/data/TOI1449_data_tfiles/calib)
2024-12-04 10:08:56.708|G| Science directory exists (Path=/media/dom/big_honkin/files/data/TOI1449_data_tfiles/science)
2024-12-04 10:08:56.708|G| LBL RV directory exists (Path=/media/dom/big_honkin/files/data/TOI1449_data_tfiles/lblrv/TYC_3154-921-1_TYC_3154-921-1)
2024-12-04 10:08:56.708|G| LBL reftable directory exists (Path=/media/dom/big_honkin/files/data/TOI1449_data_tfiles/lblreftable)
2024-12-04 10:08:56.709|G| LBL rdb directory exists (Path=/media/dom/big_honkin/files/data/TOI1449_data_tfiles/lblrdb)
2024-12-04 10:08:56.709|G| Plot directory exists (Path=/media/dom/big_honkin/files/data/TOI1449_data_tfiles/plots)
2024-12-04 10:08:56.709|G| Model directory exists (Path=/media/dom/big_honkin/files/data/TOI1449_data_tfiles/models)
2024-12-04 10:08:56.710|G| Science object directory exists (Path=/media/dom/big_honkin/files/data/TOI1449_data_tfiles/science/TYC_3154-921-1)

But I get a KeyError, even though I know this key exists in my *t.fits data files, which are in the appropriate subfolder. Here's a full traceback: 

 > 2024-12-04 10:08:57.262|E| Unexpected lbl_compute.py error: <class 'KeyError'>: 'MJDMID'
Traceback (most recent call last):
  File "/home/dom/research/TOI1449/lbl/lbl/recipes/lbl_compute.py", line 82, in main
    namespace = __main__(inst)
  File "/home/dom/research/TOI1449/lbl/lbl/recipes/lbl_compute.py", line 140, in __main__
    science_files = inst.sort_science_files(science_files)
  File "/home/dom/research/TOI1449/lbl/lbl/instruments/spirou.py", line 502, in sort_science_files
    mid_exp_time = float(sci_hdr[self.params['KW_MID_EXP_TIME']])
  File "/home/dom/research/TOI1449/lbl/lbl/core/io.py", line 85, in __getitem__
    return self.data[key]
KeyError: 'MJDMID'

 > During handling of the above exception, another exception occurred:

 > Traceback (most recent call last):
  File "/media/dom/big_honkin/files/data/TOI1449_data_tfiles/wrap/lbl_wrap.py", line 140, in <module>
    lbl_wrap(rparams)
  File "/home/dom/research/TOI1449/lbl/lbl/recipes/lbl_wrap.py", line 224, in main
    lbl_compute.main(instrument=instrument, data_dir=data_dir,
  File "/home/dom/research/TOI1449/lbl/lbl/recipes/lbl_compute.py", line 88, in main
    raise LblException(emsg.format(*eargs))
lbl.core.base_classes.LblException: Unexpected lbl_compute.py error: <class 'KeyError'>: 'MJDMID'

Any help you can offer would be appreciated! Let me know if you need any other details from me.

**Comment by njcuk9999** [comment]
Okay the error displayed isn't very helpful, but my first guess would be you have a `.fits` file in your science directory which isn't a t.fits, could you do a `ls` of this directory: `/media/dom/big_honkin/files/data/TOI1449_data_tfiles/science`

Even better would be a `dfits *.fits | fitsort MJDMID`   (if you're in the lbl-env this should work)

**Comment by doddo15** [comment]
The only thing in the directory you mention is the sub-directory for the specific target (i.e. TYC_3154-921-1). Within that sub-directory there are 200 files, all of which are *t.fits

Here's the output I get for running `dfits *.fits | fitsortr MJDMID`. The long story short is that visual inspection shows all of these are *t.fits and they appear to have good MJDMID values:

> FILE         	MJDMID            	
2584258t.fits	59266.65600465972 	
2584259t.fits	59266.661486859724	
2584260t.fits	59266.66697115973 	
2584261t.fits	59266.67251805973 	
2585922t.fits	59276.65509475973 	
2585923t.fits	59276.660642259725	
2585924t.fits	59276.666189259726	
2585925t.fits	59276.67167365972 	
2600686t.fits	59293.63720915972 	
2600687t.fits	59293.64269275973 	
2600688t.fits	59293.648176259725	
2600689t.fits	59293.65366515973 	
2600835t.fits	59294.61976665972 	
2600836t.fits	59294.625249059725	
2600837t.fits	59294.63073215973 	
2600838t.fits	59294.63425050417 	
2600839t.fits	59294.63534362778 	
2601031t.fits	59295.642961859725	
2601032t.fits	59295.64850915973 	
2601033t.fits	59295.65399225972 	
2601034t.fits	59295.65954005972 	
2601174t.fits	59296.607844759725	
2601175t.fits	59296.613326759725	
2601176t.fits	59296.61880985973 	
2601177t.fits	59296.62429395973 	
2601389t.fits	59297.61755805973 	
2601390t.fits	59297.623041559724	
2601391t.fits	59297.62852385973 	
2601392t.fits	59297.63400815972 	
2601393t.fits	59297.639490259724	
2601394t.fits	59297.64497395972 	
2601395t.fits	59297.65045565973 	
2601396t.fits	59297.65593935973 	
2601672t.fits	59299.60550735972 	
2601673t.fits	59299.61098985973 	
2601674t.fits	59299.61647255973 	
2601675t.fits	59299.621956259725	
2601676t.fits	59299.62743875972 	
2601677t.fits	59299.632921859724	
2601678t.fits	59299.638404759724	
2601679t.fits	59299.64388805973 	
2602178t.fits	59303.63778165972 	
2602179t.fits	59303.643264759725	
2602180t.fits	59303.648748459724	
2602181t.fits	59303.654295459724	
2602385t.fits	59304.63807925973 	
2602386t.fits	59304.64356115973 	
2602387t.fits	59304.64888358657 	
2602596t.fits	59305.612961659725	
2602597t.fits	59305.61850705973 	
2602598t.fits	59305.623989459724	
2602599t.fits	59305.629472359724	
2606098t.fits	59326.548414059725	
2606099t.fits	59326.553897959726	
2606100t.fits	59326.55938025973 	
2606101t.fits	59326.56492795973 	
2606102t.fits	59326.570411659726	
2606103t.fits	59326.575894359725	
2606104t.fits	59326.58143495973 	
2606105t.fits	59326.58692755973 	
2606560t.fits	59328.599195159724	
2606561t.fits	59328.60467655973 	
2606562t.fits	59328.61015845973 	
2606563t.fits	59328.61564255972 	
2606564t.fits	59328.62112525973 	
2606565t.fits	59328.62660805973 	
2606566t.fits	59328.632091559724	
2606567t.fits	59328.63757405973 	
2606754t.fits	59329.584007959726	
2606755t.fits	59329.58949105973 	
2606756t.fits	59329.59497435972 	
2606757t.fits	59329.600521459724	
2606758t.fits	59329.606007459726	
2606759t.fits	59329.611487459726	
2606760t.fits	59329.616971159725	
2606761t.fits	59329.622453259726	
2607058t.fits	59331.601178959725	
2607059t.fits	59331.606661059726	
2607060t.fits	59331.612144559724	
2607061t.fits	59331.61762715973 	
2607062t.fits	59331.623110659726	
2607063t.fits	59331.62859315972 	
2607064t.fits	59331.63407685972 	
2607065t.fits	59331.63955975972 	
2607230t.fits	59332.60973145973 	
2607231t.fits	59332.615214959726	
2607232t.fits	59332.62069805973 	
2607233t.fits	59332.62618115973 	
2607669t.fits	59334.52182265973 	
2607670t.fits	59334.52730575972 	
2607671t.fits	59334.532852859724	
2607672t.fits	59334.53840065972 	
2607909t.fits	59335.57778765973 	
2607910t.fits	59335.58326995972 	
2607911t.fits	59335.588753259726	
2607912t.fits	59335.59423755972 	
2608091t.fits	59336.60382175972 	
2608092t.fits	59336.60930505973 	
2608093t.fits	59336.61478845972 	
2608094t.fits	59336.620271759726	
2608281t.fits	59337.60095745973 	
2608282t.fits	59337.60644435973 	
2608283t.fits	59337.61192535973 	
2608284t.fits	59337.61747135973 	
2618418t.fits	59385.415107459725	
2618419t.fits	59385.42059165973 	
2618420t.fits	59385.42607365973 	
2618421t.fits	59385.43155755973 	
2618617t.fits	59386.406696759725	
2618618t.fits	59386.41217905973 	
2618619t.fits	59386.41766295973 	
2618620t.fits	59386.42314695972 	
2618818t.fits	59387.47736915972 	
2618819t.fits	59387.48285205972 	
2618820t.fits	59387.488334559726	
2618821t.fits	59387.49381775973 	
2619014t.fits	59388.40528955973 	
2619015t.fits	59388.41077245973 	
2619016t.fits	59388.416255959724	
2619017t.fits	59388.42173865972 	
2619228t.fits	59389.49615195973 	
2619229t.fits	59389.50163685973 	
2619230t.fits	59389.50711875973 	
2619231t.fits	59389.51266675973 	
2619530t.fits	59390.41871995972 	
2619531t.fits	59390.42420305972 	
2619532t.fits	59390.42968575972 	
2619533t.fits	59390.435169059725	
2619739t.fits	59391.50700345972 	
2619740t.fits	59391.51248615973 	
2619741t.fits	59391.51796895973 	
2619742t.fits	59391.523452259724	
2619930t.fits	59392.52613615972 	
2619931t.fits	59392.53161905972 	
2619932t.fits	59392.537102359725	
2619933t.fits	59392.542585259725	
2620119t.fits	59393.47508525973 	
2620120t.fits	59393.480568859726	
2620121t.fits	59393.48605125972 	
2620122t.fits	59393.49159875973 	
2620302t.fits	59394.429519059726	
2620303t.fits	59394.43500155972 	
2620304t.fits	59394.44048505973 	
2620305t.fits	59394.445967759726	
2620541t.fits	59395.55792505972 	
2620542t.fits	59395.56340705972 	
2620543t.fits	59395.568890359726	
2620544t.fits	59395.574438059724	
2620714t.fits	59396.430177359725	
2620715t.fits	59396.435659359726	
2620716t.fits	59396.441143259726	
2620717t.fits	59396.44662555972 	
2620925t.fits	59397.43505285973 	
2620926t.fits	59397.440537159724	
2620927t.fits	59397.44601945973 	
2620928t.fits	59397.45150275972 	
2620929t.fits	59397.45698625973 	
2620930t.fits	59397.46253345972 	
2620931t.fits	59397.468016559724	
2620932t.fits	59397.47349985973 	
2623406t.fits	59412.46234495973 	
2623407t.fits	59412.467828459725	
2623408t.fits	59412.47331105972 	
2623409t.fits	59412.478794259725	
2623587t.fits	59413.42348715972 	
2623588t.fits	59413.428971559726	
2623589t.fits	59413.43445375973 	
2623590t.fits	59413.439939159725	
2623844t.fits	59414.543960159725	
2623845t.fits	59414.549443259726	
2623846t.fits	59414.55492925973 	
2623847t.fits	59414.560408759724	
2623848t.fits	59414.56589145972 	
2623849t.fits	59414.571375459724	
2623850t.fits	59414.57685875973 	
2623851t.fits	59414.582341559726	
2624012t.fits	59415.40743955973 	
2624013t.fits	59415.41292305972 	
2624014t.fits	59415.41840525973 	
2624015t.fits	59415.42388885972 	
2624016t.fits	59415.42937215973 	
2624017t.fits	59415.43485455972 	
2624018t.fits	59415.44033765973 	
2624019t.fits	59415.44582015972 	
2624732t.fits	59420.41563345973 	
2624733t.fits	59420.42111625973 	
2624734t.fits	59420.42660225972 	
2624735t.fits	59420.432146659725	
2624736t.fits	59420.43763115972 	
2624737t.fits	59420.44311305972 	
2624738t.fits	59420.44859605972 	
2624739t.fits	59420.45407875972 	
2624938t.fits	59422.46570405972 	
2624939t.fits	59422.47125155973 	
2624940t.fits	59422.47673755972 	
2624941t.fits	59422.48228155972 	
2624942t.fits	59422.48776725973 	
2624943t.fits	59422.49331225973 	
2624944t.fits	59422.49879535972 	
2624945t.fits	59422.50434305973

**Comment by doddo15** [comment]
I see you added a commit which will show which file throws the error. I can pull the new code and see if this works.

**Comment by doddo15** [comment]
I pulled this branch and identified the files which were bad (there were 12 of them out of 200). They did not contain the MJDMID times, so I removed them from the science directory and the code now appears to be running as normal. The issue seems to have stemmed from my files and not from lbl, but thanks for writing that flag!

**Comment by njcuk9999** [comment]
I'd be interested to know which files didn't contain MJDMID - considering your dfits command above showed they all had them. I'd like to confirm they are t.fits files - as t.fits from APERO should contain MJDMID.

**Comment by doddo15** [comment]
The search did confirm that all files had MJDMID, but the 12 files identified were different. From the outset, I noticed that the 12 files were smaller in size (6.6 MB instead of 18.4 MB for the other 188 files). I inspected one of the different fits files, finding it had the following `hdul.info()`:

> Filename: bad_files/2600838t.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     512   ()      
  1  FluxAB        1 ImageHDU       520   (4088, 49)   float64   
  2  WaveAB        1 ImageHDU        27   (4088, 49)   float64   
  3  BlazeAB       1 ImageHDU        21   (4088, 49)   float64   
  4  Recon         1 ImageHDU       520   (4088, 49)   float64   

Using a key search, I found that the the MJDMID was only found in the PRIMARY.

Whereas a typical *t.fits file contained the following info:

> Filename: [/media/dom/big_honkin/files/data/TOI1449_data_tfiles/2624945t.fits]
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     512   ()      
  1  FluxAB        1 ImageHDU      1092   (4088, 49)   float64   
  2  WaveAB        1 ImageHDU       802   (4088, 49)   float64   
  3  BlazeAB       1 ImageHDU       349   (4088, 49)   float64   
  4  Recon         1 ImageHDU      1092   (4088, 49)   float64   
  5  OHLine        1 ImageHDU      1092   (4088, 49)   float64   
  6  FluxA         1 ImageHDU      1092   (4088, 49)   float64   
  7  WaveA         1 ImageHDU       802   (4088, 49)   float64   
  8  BlazeA        1 ImageHDU       349   (4088, 49)   float64   
  9  FluxB         1 ImageHDU      1092   (4088, 49)   float64   
 10  WaveB         1 ImageHDU       802   (4088, 49)   float64   
 11  BlazeB        1 ImageHDU       349   (4088, 49)   float64

And the key MJDMID was found in every HDU. 

That difference must have led to LBL not knowing how to handle these files. It doesn't seem to be a download error, because I just redownloaded the file from CADC and it's the same.

**Comment by njcuk9999** [comment]
So I think this is worth contacting CFHT about, all t.fits files should be exactly the same size and have exactly the same extensions. I think it is worth CFHT re-processing those 12 files.

This being said, it should still have worked in LBL if the PRIMARY header had the MJDMID key. 

Could you email me one of the broken files? (e.g. `Filename: bad_files/2600838t.fits`) I want to see what is going on with it!
